

echo -ne "🔐 Loading terminal"
for i in {1..3}; do echo -ne "."; sleep 0.2; done
clear



# HackerOS-Welcome
cat << "EOF"
┌───[ H A C K E R O S ]──────────────────────────────────────────────┐
│                                                                    │
│ ██╗  ██╗ █████╗  ██████╗██╗  ██╗███████╗██████╗  ██████╗ ███████╗  │
│ ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔═══██╗██╔════╝  │
│ ███████║███████║██║     █████╔╝ █████╗  ██████╔╝██║   ██║███████╗  │
│ ██╔══██║██╔══██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗██║   ██║╚════██║  │
│ ██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║  ██║╚██████╔╝███████║  │
│ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  │
│                                                                    │
└───[ SYSTEM READY ]─────────────────────────────────────────────────┘

       ══════════════════════════════════════════════════
       ║      W E L C O M E   T O   H A C K E R O S     ║
       ║                   v2.7                         ║
       ══════════════════════════════════════════════════

┗┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┛
> Secure, fast, game-ready. Updates done. You decide.
> Welcome aboard, operator — HackerOS Team
┗┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┛

[ NETWORK LINKS ]
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
Website:  https://hackeros.webnode.page
Discord:  https://discord.gg/8yHNcBaEKy
X:        https://x.com/hackeros_linux
GitHub:   https://github.com/HackerOS-Linux-System/
Reddit:   https://www.reddit.com/r/HackerOS/
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅

[ SYSTEM COMMANDS ]
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
Command                    | Description
---------------------------+----------------------------------------
hacker-unpack             | Installs tools for gaming, cybersecurity, add-ons, and development
hacker-commands           | Displays list of available commands
hacker-update             | Updates the system
hacker-addons             | Installs various add-ons
hacker-devtools           | Installs development tools
hacker-unpack-gaming      | Installs gaming tools
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
EOF



#Custom-Commands


#hacker-unpack
alias hacker-unpack="&& hacker-unpack-cybersecurity && hacker-unpack-gaming && hacker-devtools && hacker-add-ons"

alias hacker-unpack-cybersecurity="hacker-update && echo ========== Penetration Tools Install ========== && sudo hacker install nmap wireshark nikto john hydra aircrack-ng sqlmap ettercap-text-only tcpdump zmap bettercap wfuzz hashcat fail2ban rkhunter chkrootkit lynis clamav tor proxychains4 httrack sublist3r macchanger inxi htop openvas openvpn && echo ========== Install Metasploit Framework ========== && sudo snap install metasploit-framework && echo ========== Install Ghidra ========== && flatpak install flathub org.ghidra_sre.Ghidra && echo ========== Hacker-Unpack-Cybersecurity Compl3te =========="

alias hacker-unpack-gaming="hacker-update && echo ========== Install OBS STUDIO and LUTRIS ========== && sudo hacker install obs-studio lutris && echo ========== STEAM installation ========== && sudo hacker install steam && echo ========== Pika Torrent installation ========== && flatpak install flathub com.pikatorrent.PikaTorrent && echo ========== Install Heroic Games Launcher ProtonTricks and Discord ========== && flatpak install flathub net.davidotek.pupgui2 && flatpak install heroicgameslauncher protontricks discord && echo ========== Install Roblox ========== && flatpak install --user https://sober.vinegarhq.org/sober.flatpakref && echo ========== Install Roblox Studio ========== flatpak install flathub org.vinegarhq.Vinegar && echo ========== Hacker-Unpack-Gaming Complete =========="

alias hacker-unpack-gaming-noroblox="hacker-update && echo ========== Install OBS STUDIO and LUTRIS ========== && sudo hacker install obs-studio lutris && echo ========== STEAM installation ========== && sudo apt install steam && echo ========== Pika Torrent installation ========== && flatpak install flathub com.pikatorrent.PikaTorrent && echo ========== Install Heroic Games Launcher ProtonTricks and Discord ========== && flatpak install flathub net.davidotek.pupgui2 && flatpak install heroicgameslauncher protontricks discord && echo ========== Hacker-Unpack-Gaming-NoRoblox Complete =========="

alias hacker-unpack-emulators="hacker-update && echo ========== Install PlayStation Emulator ========== flatpak install shadPS4 && echo ========== Install Emulator Nintendo ========== && flatpak install flathub io.github.ryubing.Ryujinx && echo ========== Install DOSBOX ========== && flatpak install flathub com.dosbox_x.DOSBox-X && echo ========== Install PlayStation 3 Emulator ========== && sudo snap install rpcs3-emu && echo ========== Hacker-Unpack-Emulators Complete =========="

alias hacker-mode-install="echo Updating System && hacker-update && flathub install heroicgameslauncher && flatpak install --user https://sober.vinegarhq.org/sober.flatpakref && flatpak install flathub xyz.hyperplay.HyperPlay && sudo hacker install lutris steam"

#hacker install gamescope steam
alias hacker-install-gamescope-steam="/usr/share/HackerOS/Scripts/Bin/hacker-install-gamescope-steam.sh"

#Hacker-SysLogs
alias hacker-syslog="echo ========== System Logs ========== && sudo journalctl -xe"

#Lista Komend
alias hacker-commands="echo ========== Commands List ==========  hacker-update hacker-unpack hacker-unpack-cybersecurity hacker-unpack-gaming hacker-unpack-gaming-noroblox hacker-syslogs hacker-unpack-emulators && echo ========== Instead of the sudo apt command you can use hacker =========="

#Hacker-DevTools
alias hacker-devtools="hacker-update && echo ========== Install Atom ========== && flatpak install flathub io.atom.Atom && echo ========== Install Dev Tools Complete =========="

#Hacker-AddOns
alias hacker-add-ons="hacker-update && echo ========== Install Wine ========== && sudo hacker install wine winetricks && echo ========== Install BoxBuddy and Winezgui ========== && flatpak install flathub io.github.dvlv.boxbuddyrs && flatpak install winezgui && flatpak install flathub it.mijorus.gearlever && echo ========== Install Add-Ons Complete =========="

#hacker-nvidia-akmod
alias nvidia-akmod="hacker-update && sudo hacker install nvidia-akmod"

#hacker-unpack-g-s
alias hacker-unpack-g-s="hacker-update && hacker-unpack-gaming && hacker-unpack-cybersecurity"

#Star-HackerOS-Cockpit
alias start-hackeros-cockpit="python3 /usr/share/HackerOS/Scripts/HackerOS-Apps/HackerOS-Cockpit/HackerOS_Cockpit.py"

# 🔥 Dark Mode dla Basha w Alacritty
export LS_COLORS="di=1;34:ln=1;36:so=1;35:pi=1;33:ex=1;32"

# 🔥 Ustawienia kolorów dla terminala
export PS1="\[\e[1;37m\]\u@\h:\[\e[1;34m\]\w\[\e[0m\]$ "

# 🎨 Funkcja do wyświetlania kolorowych klikalnych linków
function link() {
    local text="$1"
    local url="$2"
    echo -e "\e[1;31m\e]8;;$url\a$text\e]8;;\a\e[0m"
}

# 🌍 Funkcja do otwierania linków w domyślnej przeglądarce
function openlink() {
    local url="$1"
    if command -v xdg-open >/dev/null; then
        xdg-open "$url" >/dev/null 2>&1 &
    elif command -v gnome-open >/dev/null; then
        gnome-open "$url" >/dev/null 2>&1 &
    elif command -v open >/dev/null; then
        open "$url" >/dev/null 2>&1 &  # macOS
    else
        echo "❌ Nie można otworzyć linku: $url"
    fi
}


# Kolory dla ls
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'

# Emoji + git
alias gs='echo 🌀 && git status'
alias gc='echo 📦 && git commit -m'
alias gp='echo ⬆️ && git push'

# Kolorowe PS1 (jeśli nie używasz Starship)
PS1='\[\e[1;32m\]\u@\h \[\e[1;34m\]\w \[\e[0;33m\]$\[\e[0m\] '
