#!/usr/bin/bash

# Exit immediately if this is a Midnight Commander (mc) subshell.
if [[ -n "$MC_SID" ]]; then
    exit 0
fi

escape() {
    sed 's/[&/\]/\\&/g' <<< "$1"
}

# Losowanie jednego pliku z tipami
TIP_FILE=$(ls "/usr/lib/HackerOS/motd/"*.md 2>/dev/null | shuf -n 1)
if [[ -f "$TIP_FILE" ]]; then

    # Informacje o edycji systemu z kcm-about-distrorc
    DISTRO_VARIANT=$(grep '^Variant=' /etc/xdg/kcm-about-distrorc | cut -d'=' -f2-)
    DISTRO_VARIANT_ESCAPED=$(escape "$DISTRO_VARIANT")

    # Wczytanie całego pliku tipa
    TIP_CONTENT=$(cat "$TIP_FILE")
    TIP_ESCAPED=$(escape "$TIP_CONTENT")

    # Renderowanie MOTD z szablonu
    sed \
      -e "s/%VARIANT%/$DISTRO_VARIANT_ESCAPED/g" \
      -e "s/%TIP%/$TIP_ESCAPED/g" \
      /usr/lib/HackerOS/motd/template/HackerOS.md \
    | tr '~' '\n' \
    | /usr/bin/glow -s usr/lib/HackerOS/motd/theme/default.json -w 78 -
fi
